version: "3.3"

services:
  aws:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      DEFAULT_REGION: us-east-1
      SERVICES: dynamodb
  application:
    image: node:14-alpine
    command: sh -c "npm install && npm run configure:dynamo"
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - 3333:3333
      - 9229:9229
      - 9228:9228
    depends_on:
      - aws
    environment:
      AWS_ACCESS_KEY_ID: "dev"
      AWS_REGION: "us-east-1"
      AWS_SECRET_ACCESS_KEY: "dev"
      NODE_ENV: "dev"
      AWS_ENDPOINT: "http://aws:4566"
      DYNAMODB_ADMIN: "http://localhost:8000/"
      TABLE_ENDPOINT: "http://aws:4566"
      TABLE_NAME: "table_local"
      X_API_KEY: "valid-api-key"
